modLoader="javafml"
loaderVersion="[38,)"
license="All rights reserved"

[[mods]]
modId="rereskillable"
version="1.3.6"
displayName="Rereskillable"
displayURL="https://www.curseforge.com/minecraft/mc-mods/rereskillable"
credits="Skillable and Reskillable"
authors="majik, LukeGrahamLandry"
description='''
Rereskillable is a simplified rewrite of Reskillable for Minecraft Forge 1.16.5.
'''

[[dependencies.rereskillable]]
    modId="forge"
    mandatory=true
    versionRange="[38,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.rereskillable]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"

[[dependencies.rereskillable]]
    modId="curios"
    mandatory=false
    versionRange="[1.16.5-4.0.5.0,)"
    ordering="AFTER"
    side="BOTH"